### PR TITLE
Switch fragment host visibility exception to warning message

### LINKED ISSUE #3160: Update for ShowNestedFragment fragmentHost.IsVisible
## 🏗 Enhancement Proposal

Remove the [`fragmentHost.IsVisible`](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Android.Support/V7.AppCompat/MvxAppCompatViewPresenter.cs#L260) constraint or allow for it to be ignored via a `MvxFragmentPresentationAttribute` property. 

### Pitch

Currently, I have an App that is working fine without this check. I needed to override `ShowNestedFragment` to remove it else it kept throwing the `InvalidOperationException`. I'm not too sure if there is something particularly special about my implementation that it all works fine with `fragmentHost.IsVisible` returning `false`. But it does not seem necessary at least not all the time. It would be nice to not have to create a custom presenter to override and remove this check.

I would like to propose adding an additional property to `MvxFragmentPresentationAttribute` to opt-out of this check, `IgnoreHostVisibility`. 

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

### PR DESCRIPTION
**Pull request by Plac3hold3r**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Feature

### :arrow_heading_down: What is the current behavior?

If fragment host was not visible at the time of inflating a nested fragment an `InvalidOperationException` was thrown.

### :new: What is the new behavior (if this is a feature change)?

Logs a warning.

### :boom: Does this PR introduce a breaking change?

Yes, if a user was expecting the exception to be thrown, now it will only log a warning.

### :bug: Recommendations for testing

See PR #3163

### :memo: Links to relevant issues/docs

Closes #3160 
Closes #3163

### :thinking: Checklist before submitting

- [X] All projects build
- [X] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [X] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [X] Rebased onto current develop

### CODE REVIEW

File: MvvmCross/Platforms/Android/Presenters/MvxAndroidViewPresenter.cs [hunk 1]
```diff
@@ -344,7 +344,7 @@ protected virtual void ShowHostActivity(MvxFragmentPresentationAttribute attribu
                 throw new NullReferenceException($"Fragment host not found when trying to show View {view.Name} as Nested Fragment");
 
             if (!fragmentHost.IsVisible)
-                throw new InvalidOperationException($"Fragment host is not visible when trying to show View {view.Name} as Nested Fragment");
+                MvxLog.Instance.Warn("Fragment host is not visible when trying to show View {0} as Nested Fragment", view.Name);
```
Comment (Cheesebaron) [inline MvvmCross/Platforms/Android/Presenters/MvxAndroidViewPresenter.cs]: Should probably be `MvxAndroidLog`

Comment (Plac3hold3r) [reply MvvmCross/Platforms/Android/Presenters/MvxAndroidViewPresenter.cs]: As `MvxAndroidViewPresenter` is part of the main MvvmCross project which has access to the default static `MvxLog` internal instance. The `MvxAppCompatViewPresenter` on the other hand sits in a different .dll which makes use of the `MvxAndroidLog` IoC resolved internal instance.

Comment (Cheesebaron) [reply MvvmCross/Platforms/Android/Presenters/MvxAndroidViewPresenter.cs]: You are right 👍
