### PR TITLE
Fix #2116 Incorrect ViewModel Init() params serialization/deserialization

### LINKED ISSUE #2116: Incorrect ViewModel Init() params serialization/deserialization
### Steps to reproduce

1. Set smartphone language to RU or any other with ',' as decimal separator.

2. Pass **double** value to ViewModel through ShowModel(Parameters param), for example 10,24

3. Compare with **double** value passed to ViewModel Init(Parameters param)

### Expected behavior
double value passed to Init() is the same

### Actual behavior
decimal value passed to Init() is not the same - **decimal separator is missed**

### Configuration

**Version:** 5.1.1

**Platform:** 
- [x] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

### PR DESCRIPTION
**Pull request by jz5**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug fix

### :arrow_heading_down: What is the current behavior?
The passed values in navigation are different from original values.

Reasons:
* Serialization with CurrentCulture,  Deserialization with InvariantCulture (#2116)
* The precision is dropped (float, double, DateTime)

### :new: What is the new behavior (if this is a feature change)?
The passed values in navigation are equal to original values.

Modified:
* Serialization/Deserialization with InvariantCulture 
* Round-trip Serialization/Deserialization

### :boom: Does this PR introduce a breaking change?
No

### :memo: Links to relevant issues/docs
#2116 

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Nuspec files were updated (when applicable)
- [ ] Rebased onto current develop

### CODE REVIEW

File: MvvmCross/Core/Core/Platform/MvxSimplePropertyDictionaryExtensionMethods.cs [hunk 1]
```diff
@@ -148,14 +149,25 @@ public static string GetPropertyValueAsString(this object input, PropertyInfo pr
...
+                return value?.ToStringInvariant();
             }
             catch (Exception suspectedMethodAccessException)
             {
                 throw suspectedMethodAccessException.MvxWrap(
                     "Problem accessing object - most likely this is caused by an anonymous object being generated as Internal - please see http://stackoverflow.com/questions/8273399/anonymous-types-and-get-accessors-on-wp7-1");
             }
         }
+
+        private static string ToStringInvariant(this object value)
```
Comment (Cheesebaron) [inline MvvmCross/Core/Core/Platform/MvxSimplePropertyDictionaryExtensionMethods.cs]: Why don't you use `Convert.ToString(value, CultureInfo.InvariantCulture)` instead of this homebrew method?

File: MvvmCross/Core/Core/Platform/MvxStringToTypeParser.cs [hunk 2]
```diff
@@ -1,4 +1,4 @@
-﻿// MvxStringToTypeParser.cs
+// MvxStringToTypeParser.cs
```
Comment (Cheesebaron) [inline MvvmCross/Core/Core/Platform/MvxStringToTypeParser.cs]: All the changes to this file are not related to the issue.

File: MvvmCross/Core/Core/Platform/MvxSimplePropertyDictionaryExtensionMethods.cs (hunk 1 above)
Comment (jz5) [inline MvvmCross/Core/Core/Platform/MvxSimplePropertyDictionaryExtensionMethods.cs]: ``Convert.ToString(value, CultureInfo.InvariantCulture)`` causes precision dropping.
So DateTime, double,  float types need to use round-trip conversion in ```ToStringInvariant```.

example
```c#
var str = Convert.ToString(double.MaxValue,  CultureInfo.InvariantCulture);
var result = double.TryParse(str, out var value); // result is false because str becomed value with low precision 
```

File: MvvmCross/Core/Core/Platform/MvxStringToTypeParser.cs (hunk 2 above)
Comment (jz5) [inline MvvmCross/Core/Core/Platform/MvxStringToTypeParser.cs]: The parameters passed to ```ShowViewModel``` are  deserialized in this class. Need ```TryParse``` with ```CultureInfo.InvariantCulture```. I added ```CultureInfo.InvariantCulture```. But with style changed...

Comment (Cheesebaron) [inline MvvmCross/Core/Core/Platform/MvxStringToTypeParser.cs]: Please don't change the style.

Comment (jz5) [inline MvvmCross/Core/Core/Platform/MvxStringToTypeParser.cs]: I pushed modified file.
