### PR TITLE
Fix NSTextView binding (for text content). Fixes #4909.

### LINKED ISSUE #4909: [Bug]: BindStringValue() does not work for NSTextView
### Description

When I try to bind string property to the NSTextView I got the warning
```
[Warning] Failed to create target binding for "binding StringValue for Text"
```

### Steps to Reproduce

1. Add `NSTextView` (not `NSTextField` but multiline text view) and wire it to the `textView` outlet.
2. Add the following binding code
     ```
     using var set = CreateBindingSet();
     set.Bind(textView).For(v=>v.BindStringValue()).To(vm => vm.Text); //Text property is `string Text{get;set;}
     ```
3. Run and check console.

### Link to public reproduction project repository

_No response_

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### PR DESCRIPTION
**Pull request by snechaev**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug fix

### :arrow_heading_down: What is the current behavior?
The content (text) binding for the NSTextView does not work.

### :new: What is the new behavior (if this is a feature change)?
The content (text) binding for the NSTextView works as expected.

### :boom: Does this PR introduce a breaking change?
No.

### :bug: Recommendations for testing
Configure bidirectional binding for the NSTextView and check the following:
* binding works in both directions
* the text caret maintains a meaningful position during the text input/pasting from the clipboard/VM updates.

### :memo: Links to relevant issues/docs
Fixes https://github.com/MvvmCross/MvvmCross/issues/4909

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### 🗒️ Additional notes:
This is better implementation of the same fix that was previously presented in https://github.com/MvvmCross/MvvmCross/pull/4911 . It's also looks more clear then changes, discussed in https://github.com/MvvmCross/MvvmCross/issues/4909 (with very minor changes of the existing `MvxPropertyInfoTargetBinding`-based binding).
* in comparison with the https://github.com/MvvmCross/MvvmCross/pull/4911 the current solution use a lot of useful checks, implemented in the `MvxConvertingTargetBinding` (including update-loop prevention and so on) and thus, in particular, it does not require manual handling of the text caret position.
* in comparison with the option, discussed in the https://github.com/MvvmCross/MvvmCross/issues/4909 the current implementation does not rely on the any `PropertyInfo` in any way (not on the declaration/inherence tree level, nor in the implementation) which makes it more reliable and easy-to-understand.

### CODE REVIEW

File: MvvmCross/Platforms/Mac/Binding/MvxMacPropertyBinding.cs [hunk 1]
```diff
@@ -14,7 +14,7 @@ internal static class MvxMacPropertyBinding
         public const string NSDatePicker_Time = "Time";
         public const string NSDatePicker_Date = "Date";
         public const string NSTextField_StringValue = "StringValue";
-        public const string NSTextView_StringValue = "StringValue";
+        public const string NSTextView_StringValue = "TextValueFakeInternalId";
```
Comment (Cheesebaron) [inline MvvmCross/Platforms/Mac/Binding/MvxMacPropertyBinding.cs:17]: I think you can revert this back to `StringValue`. This way if someone uses `set.Bind("StringValue").To(vm => vm.Text)` it would still work for them.

It is used to tie together the `MvxNSTextViewTextTargetBinding` class and the binding.

**Review by Cheesebaron — CHANGES_REQUESTED** [review]

File: MvvmCross/Platforms/Mac/Binding/MvxMacPropertyBinding.cs (hunk 1 above)
Comment (snechaev) [reply MvvmCross/Platforms/Mac/Binding/MvxMacPropertyBinding.cs]: Good point! Fixed.

**Review by Cheesebaron — APPROVED** [review]
