### PR TITLE
Fix MvxTabBarViewController.VisibleUIViewController

### LINKED ISSUE #1812: MvxTabBarViewController.VisibleUIViewController throws for tabs without a navigation controller
Problem is on line 115:

    var topViewController = (SelectedViewController as UINavigationController).TopViewController;

This assumes every tab is wrapped in a UINavigationController, which can be disabled using the presentation attribute:

        [MvxTabPresentation(
            TabName = "Targets",
            TabIconName = "TabBarItemTargets",
            WrapInNavigationController = false)]

If we do, the above lines throws an NRE when the selected tab is one without a navigation controller.

### PR DESCRIPTION
**Pull request by nmilcoff**
Fixes #1812

### CODE REVIEW

File: MvvmCross/iOS/iOS/Views/MvxTabBarViewController.cs [hunk 1]
```diff
@@ -112,7 +112,10 @@ public virtual UIViewController VisibleUIViewController
         {
             get
             {
-                var topViewController = (SelectedViewController as UINavigationController).TopViewController;
+                var topViewController = SelectedViewController is UINavigationController
```
Comment (Cheesebaron) [inline MvvmCross/iOS/iOS/Views/MvxTabBarViewController.cs]: Couldn't you just have done:

```
var topViewController = (SelectedController as UINavigationController)?.TopViewController ?? SelectedViewController;
```

That seems much cleaner.

Comment (Cheesebaron) [inline MvvmCross/iOS/iOS/Views/MvxTabBarViewController.cs]: Also please rebase instead of merging develop in.

Comment (nmilcoff) [inline MvvmCross/iOS/iOS/Views/MvxTabBarViewController.cs]: Yes, you're right! Thanks
