### PR TITLE
Fix MvxAutoCompleteTextView not returning results

### LINKED ISSUE #3008: MvxAutoCompleteTextView PartialText never changes after initial setting
### Expected behavior
PartialText's binding should change when the user types

### Reproduction steps
Create MvxAutoCompleteTextView and bind PartialText.
Type some stuff.

### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

### PR DESCRIPTION
**Pull request by Cheesebaron**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug fix

### :arrow_heading_down: What is the current behavior?
MvxAutoCompleteTextView doesn't return any results at all when typing in it

### :new: What is the new behavior (if this is a feature change)?
Returns matching results

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
1. Add a MvxAutoCompleteTextView
2. Bind `ItemsSource` to list of items that implement `ToString()` for filtering
3. Type stuff that the items contain

This now also allows someone to provide different filtering logic, rather than just matching on `ToString()` by setting `FilterPredicate` on the `MvxFilteringAdapter`.

### :memo: Links to relevant issues/docs
Fixes #3008 

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

File: MvvmCross/Binding/Extensions/MvxEnumerableExtensions.cs [hunk 1]
```diff
@@ -84,5 +86,25 @@ public static object ElementAt(this IEnumerable items, int position)
 
             return enumerator.Current;
         }
+
+        public static IEnumerable Filter(this IEnumerable items, Func<object, bool> predicate)
+        {
+            if (items == null)
+                return null;
```
Comment (nickrandolph) [inline MvvmCross/Binding/Extensions/MvxEnumerableExtensions.cs]: Would it be better to return empty array instead of null - it'll cause few breaks for developers that fail to do a null check on the returned result

File: MvvmCross/Binding/Extensions/MvxEnumerableExtensions.cs [hunk 2]
```diff
@@ -84,5 +86,25 @@ public static object ElementAt(this IEnumerable items, int position)
...
+
+            var enumerator = items.GetEnumerator();
```
Comment (nickrandolph) [inline MvvmCross/Binding/Extensions/MvxEnumerableExtensions.cs]: Whilst perhaps not as efficient from a performance perspective, a simple Where linq clause would make this easier to follow?

File: MvvmCross/Platforms/Android/Binding/Views/MvxFilteringAdapter.cs [hunk 3]
```diff
@@ -148,6 +156,35 @@ public override Object GetItem(int position)
...
+                var element = FilteredItemsSource?.ElementAt(position);
+                return element;
+            }
+        }
+
+        public override int GetPosition(object item)
+        {
+            lock (_syncLock)
+            {
+                var pos = FilteredItemsSource?.GetPosition(item) ?? 0;
```
Comment (nickrandolph) [inline MvvmCross/Platforms/Android/Binding/Views/MvxFilteringAdapter.cs]: Should default be 0 or -1

File: MvvmCross/Binding/Extensions/MvxEnumerableExtensions.cs (hunk 2 above)
Comment (Cheesebaron) [reply MvvmCross/Binding/Extensions/MvxEnumerableExtensions.cs]: Linq queries do not work on non-generic IEnumerable, that is why we have these extensions in the first place.

Comment (nickrandolph) [reply MvvmCross/Binding/Extensions/MvxEnumerableExtensions.cs]: doh! yeh of course, it requires generics. We should be able to at least use a basic for loop here, right?

File: MvvmCross/Platforms/Android/Binding/Views/MvxFilteringAdapter.cs (hunk 3 above)
Comment (Cheesebaron) [reply MvvmCross/Platforms/Android/Binding/Views/MvxFilteringAdapter.cs]: Hmm, this is used in `GetItem` and `GetRawItem` to get the element. Not sure what the appropriate default value should be here. If it is 0 and the ItemsSource contains 0 items you will get a Index error, the same with -1. However, if it contains items 0 could return a wrong item and -1 would still throw a Index error. Not sure what is preferred here.
