### PR TITLE
Find resource type based on Android.Runtime.ResourceDesignerAttribute

### LINKED ISSUE #2772: MvvmCross doesn't work with F# Android app resources
### Steps to reproduce :scroll:

1. Clone this repo [Fsharp Droid project with MvvmCross](https://github.com/willsam100/MvvmFsharpDroid)

2. Build

3. Run

### Expected behavior :thinking:

The application should launch

### Actual behavior :bug:
Tell us what happens instead

```
[mono] MvvmCross.Platform.Exceptions.MvxException: Unable to find resource type - MvvmFormsAppFsharp.Droid.Resource. Please check if your setup class is in your application's root namespace. [mono] at MvvmCross.Binding.Droid.ResourceHelpers.MvxAppResourceTypeFinder.Find () [0x0002a] in D:\git\MvvmCross\MvvmCross\Binding\Droid\ResourceHelpers\MvxAppResourceTypeFinder.cs:23 [mono] at MvvmCross.Binding.Droid.ResourceHelpers.MvxAndroidBindingResource..ctor () [0x0000b] in D:\git\MvvmCross\MvvmCross\Binding\Droid\ResourceHelpers\MvxAndroidBindingResource.cs:31 [mono] at MvvmCross.Binding.Droid.ResourceHelpers.MvxAndroidBindingResource.Initialize () [0x00008] in 
```

### Configuration :wrench:

**Version:** 5.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

### PR DESCRIPTION
**Pull request by nosami**
instead of using hardcoded name for resource type. Fixes #2772

I haven't tested this code. I haven't even compiled it (couldn't build on OSX) :) It looks right to me though.

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Fixes #2772 - The resource type name can be defined by the user, it might not be "Resource"

### :arrow_heading_down: What is the current behavior?

Can't use MvvmCross with F#

### :memo: Links to relevant issues/docs

#2772 
https://github.com/xamarin/xamarin-android/issues/1513#issuecomment-379391085

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Rebased onto current develop
https://github.com/xamarin/xamarin-android/issues/1513#issuecomment-379391085

### CODE REVIEW

**Comment by nosami** [comment]
@Cheesebaron : did you try this code? I couldn't compile.

File: MvvmCross/Platforms/Android/Binding/ResourceHelpers/MvxAppResourceTypeFinder.cs [hunk 1]
```diff
@@ -1,22 +1,35 @@
-// Licensed to the .NET Foundation under one or more agreements.
+﻿// Licensed to the .NET Foundation under one or more agreements.
 // The .NET Foundation licenses this file to you under the MS-PL license.
 // See the LICENSE file in the project root for more information.
 
 using System;
+using System.Reflection;
```
Comment (Cheesebaron) [inline MvvmCross/Platforms/Android/Binding/ResourceHelpers/MvxAppResourceTypeFinder.cs]: missing system.linq

File: MvvmCross/Platforms/Android/Binding/ResourceHelpers/MvxAppResourceTypeFinder.cs [hunk 2]
```diff
@@ -1,22 +1,35 @@
...
 
 namespace MvvmCross.Platforms.Android.Binding.ResourceHelpers
 {
     public class MvxAppResourceTypeFinder : IMvxAppResourceTypeFinder
     {
+        private Type FindResourceType(Assembly assembly)
+        {
+            var att = assembly.CustomAttributes.FirstOrDefault(ca =>
+                          ca.AttributeType.FullName == "Android.Runtime.ResourceDesignerAttribute" &&
+                          ca.Properties.First(p => p.Name == "IsApplication").Argument.Value == true);
```
Comment (Cheesebaron) [inline MvvmCross/Platforms/Android/Binding/ResourceHelpers/MvxAppResourceTypeFinder.cs]: `ca.Properties` doesn't seem to be present.

File: MvvmCross/Platforms/Android/Binding/ResourceHelpers/MvxAppResourceTypeFinder.cs [hunk 3]
```diff
@@ -1,22 +1,35 @@
...
+
+            if (att != null)
+            {
+                var resourceType = assembly.Modules.SelectMany(m => m.Types).FirstOrDefault(
+                    t => t.FullName == (string)att.ConstructorArguments.First().Value);
+                return resourceType;
+            }
```
Comment (Cheesebaron) [inline MvvmCross/Platforms/Android/Binding/ResourceHelpers/MvxAppResourceTypeFinder.cs]: Not all code paths return.

**Comment by Cheesebaron** [comment]
Can't you maybe try to just grab the code put it in a Android App and experiment with it there? Then plop it into MvvmCross? As for building on Mac, VSfM doesn't like our project because of UWP I think.

**Comment by nosami** [comment]
@Cheesebaron : Yes, I'll do that. Thanks!

File: MvvmCross/Platforms/Android/Binding/ResourceHelpers/MvxAppResourceTypeFinder.cs (hunk 2 above)
Comment (nosami) [reply MvvmCross/Platforms/Android/Binding/ResourceHelpers/MvxAppResourceTypeFinder.cs]: heh - this is Mono.Cecil API, not System.Reflection 🤪

Comment (Cheesebaron) [reply MvvmCross/Platforms/Android/Binding/ResourceHelpers/MvxAppResourceTypeFinder.cs]: Should still be fine to look for `ResourceDesignerAttribute`. However, instead of checking for `IsApplication` maybe just assume that the assembly with `Setup` file, is the Application.

Comment (nosami) [reply MvvmCross/Platforms/Android/Binding/ResourceHelpers/MvxAppResourceTypeFinder.cs]: OK. That makes it easier. I know nothing about MvvmCross by the way - never used it. My C# is a little rusty too :)

Comment (nosami) [reply MvvmCross/Platforms/Android/Binding/ResourceHelpers/MvxAppResourceTypeFinder.cs]: image
Let me get this into the PR. Will rebase.

**Comment by Cheesebaron** [comment]
@nosami I'll take a look later today 😄

**Comment by nosami** [comment]
@nickrandolph - thanks!
